import request from 'supertest'; import app from '../src/app.js'; import User from '../src/models/User.js'; import Vehicle from '../src/models/Vehicle.js'; import { issueToken } from '../src/services/authService.js';
const register = { name: 'Asha Dealer', email: 'asha@example.com', password: 'securepass1' };
const vehicle = { vehicleId: 'CAR-001', make: 'Toyota', model: 'RAV4', category: 'SUV', price: 32000, quantity: 2 };
const auth = (token) => ({ Authorization: `Bearer ${token}` });
async function adminToken() { const admin = await User.create({ ...register, email: 'admin@example.com', role: 'admin' }); return issueToken(admin); }
describe('authentication', () => {
  test('registers safely and prevents duplicate emails', async () => { const first = await request(app).post('/api/auth/register').send(register); expect(first.status).toBe(201); expect(first.body.data.user.password).toBeUndefined(); const duplicate = await request(app).post('/api/auth/register').send(register); expect(duplicate.status).toBe(409); });
  test('validates registration and issues a JWT on login', async () => { expect((await request(app).post('/api/auth/register').send({ email: 'bad' })).status).toBe(400); await request(app).post('/api/auth/register').send(register); const response = await request(app).post('/api/auth/login').send({ email: register.email, password: register.password }); expect(response.status).toBe(200); expect(response.body.data.token).toBeTruthy(); });
  test('rejects incorrect login and protected routes without valid token', async () => { await request(app).post('/api/auth/register').send(register); expect((await request(app).post('/api/auth/login').send({ email: register.email, password: 'wrongpass' })).status).toBe(401); expect((await request(app).get('/api/vehicles')).status).toBe(401); expect((await request(app).get('/api/vehicles').set(auth('bad'))).status).toBe(401); });
});
describe('vehicle inventory', () => {
  test('admin creates, searches, updates, and deletes vehicle', async () => { const token = await adminToken(); expect((await request(app).post('/api/vehicles').set(auth(token)).send(vehicle)).status).toBe(201); expect((await request(app).post('/api/vehicles').set(auth(token)).send(vehicle)).status).toBe(409); const searched = await request(app).get('/api/vehicles/search?make=toyota&minPrice=30000').set(auth(token)); expect(searched.body.data.vehicles).toHaveLength(1); const id = searched.body.data.vehicles[0]._id; expect((await request(app).put(`/api/vehicles/${id}`).set(auth(token)).send({ quantity: 4 })).status).toBe(200); expect((await request(app).delete(`/api/vehicles/${id}`).set(auth(token))).status).toBe(200); });
  test('enforces role authorization and vehicle validation', async () => { const user = await User.create(register); const userToken = issueToken(user); expect((await request(app).post('/api/vehicles').set(auth(userToken)).send(vehicle)).status).toBe(403); const admin = await adminToken(); expect((await request(app).post('/api/vehicles').set(auth(admin)).send({ ...vehicle, quantity: -1 })).status).toBe(400); });
  test('purchases atomically, rejects stockout, and permits only admins to restock', async () => { const admin = await adminToken(); const created = await request(app).post('/api/vehicles').set(auth(admin)).send({ ...vehicle, quantity: 1 }); const id = created.body.data.vehicle._id; const user = await User.create(register); const userToken = issueToken(user); const bought = await request(app).post(`/api/vehicles/${id}/purchase`).set(auth(userToken)); expect(bought.status).toBe(200); expect(bought.body.data.vehicle.quantity).toBe(0); expect((await request(app).post(`/api/vehicles/${id}/purchase`).set(auth(userToken))).status).toBe(409); expect((await request(app).post(`/api/vehicles/${id}/restock`).set(auth(userToken)).send({ quantity: 2 })).status).toBe(403); expect((await request(app).post(`/api/vehicles/${id}/restock`).set(auth(admin)).send({ quantity: 0 })).status).toBe(400); expect((await request(app).post(`/api/vehicles/${id}/restock`).set(auth(admin)).send({ quantity: 2 })).body.data.vehicle.quantity).toBe(2); });
  test('does not show out-of-stock cars in available results', async () => { const admin = await adminToken(); await Vehicle.create({ ...vehicle, quantity: 0 }); const result = await request(app).get('/api/vehicles').set(auth(admin)); expect(result.body.data.vehicles).toHaveLength(0); });
});
describe('car dashboard API', () => {
  const car = { make: 'Toyota', model: 'Camry', year: 2023, price: 1200000, mileage: 18000, fuelType: 'Petrol', transmission: 'Automatic', color: 'White', condition: 'Used', status: 'Available' };
  test('supports protected car CRUD, combined search/filter/sort, and statistics', async () => { const user = await User.create(register); const token = issueToken(user); expect((await request(app).get('/api/cars')).status).toBe(401); const created = await request(app).post('/api/cars').set(auth(token)).send(car); expect(created.status).toBe(201); const id = created.body.data.car._id; const found = await request(app).get('/api/cars?search=camry&fuelType=Petrol&sort=price_asc').set(auth(token)); expect(found.body.data.cars).toHaveLength(1); expect((await request(app).get(`/api/cars/${id}`).set(auth(token))).status).toBe(200); expect((await request(app).put(`/api/cars/${id}`).set(auth(token)).send({ status: 'Sold' })).status).toBe(200); const stats = await request(app).get('/api/cars/stats').set(auth(token)); expect(stats.body.data.statistics.soldCars).toBe(1); expect((await request(app).delete(`/api/cars/${id}`).set(auth(token))).status).toBe(200); expect((await request(app).get(`/api/cars/${id}`).set(auth(token))).status).toBe(404); });
});
